### ISSUE TITLE
🎂 [Release] Release v3.1.3-XXX - Fix Event Datetime etc.

### ISSUE THREAD

**Issue by Tirokk** [Yunite-Net/yunite.me#11]
## RELEASE

Release v3.1.3-XXX - Fix Event Datetime etc.

### Todo

- [ ] main code:
  - [ ] configurations in `deployment\constants\.` are not used in backend by Dockerfile?
    - [ ] it's not working for `groups.ts` and `DESCRIPTION_WITHOUT_HTML_LENGTH_MIN` at the end
- [ ] set kubernetes config to new cluster
- [ ] set new version and build number
